import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import style from './page.module.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={style.page}>
          <div className={style.layout}>
            <header className={style.header}>
              Root header
            </header>
            <section className={style.section}>
              {children}
            </section>
          </div>
        </div>
      </body>
    </html>
  );
}
